"""Domain models for TestCraft."""

from .manual_fix import (
    ManualFixContextAttachment,
    ManualFixRecommendation,
    ManualFixRequest,
)
from .models import (
    AnalysisReport,
    Budget,
    ContextPack,
    Conventions,
    CoverageResult,
    DeterminismConfig,
    Focal,
    GenerationResult,
    GwtSnippets,
    ImportMap,
    IOPolicy,
    PlanningRequest,
    PlanningResult,
    PlanOption,
    PropertyContext,
    RankedMethod,
    RefineOutcome,
    ResolvedDef,
    Target,
    TestBundle,
    TestCraftError,
    TestElement,
    TestElementType,
    TestGenerationPlan,
)

__all__ = [
    # Manual fix models
    "ManualFixContextAttachment",
    "ManualFixRecommendation",
    "ManualFixRequest",
    # Core models
    "AnalysisReport",
    "Budget",
    "ContextPack",
    "Conventions",
    "CoverageResult",
    "DeterminismConfig",
    "Focal",
    "GenerationResult",
    "GwtSnippets",
    "ImportMap",
    "IOPolicy",
    "PlanningRequest",
    "PlanningResult",
    "PlanOption",
    "PropertyContext",
    "RankedMethod",
    "RefineOutcome",
    "ResolvedDef",
    "Target",
    "TestBundle",
    "TestCraftError",
    "TestElement",
    "TestElementType",
    "TestGenerationPlan",
]
